import { library } from '@fortawesome/fontawesome-svg-core';

//Font Awesome Icons
import {
  faCubes,
  faBox,
  faBoxOpen,
  faShippingFast,
  faAnchor,
  faTrashAlt,
  faCog,
  faSearch,
  faSignOutAlt,
  faTag,
  faAddressCard,
  faMoneyBillAlt,
  faHandHoldingUsd,
  faEllipsisH,
  faReceipt,
  faScroll,
  faEdit,
  faPlus,
  faMinus,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronCircleRight,
  faChevronCircleDown,
  faCoins,
  faTimes,
  faTimesCircle,
  faInventory,
  faMapMarkerAlt,
  faQuoteLeft,
  faBrackets,
  faCheck,
  faCloudUpload,
  faChartPie,
  faAsterisk,
  faUserCog,
  faDollarSign,
  faCheckCircle,
  faMailbox,
  faUserLock,
  faParachuteBox,
  faPlusCircle
} from '@fortawesome/pro-solid-svg-icons';

import {
  fal,
  faBarcodeRead,
  faChevronDown as falFaChevronDown
} from '@fortawesome/pro-light-svg-icons';

import {
  far,
  faBoxUsd,
  faTally,
  faCommentAltLines,
  faIdCardAlt,
  faMinusCircle,
  faImages,
  faCircle,
  faExclamationCircle,
  faInfoCircle,
  faBoxFull,
  faTruckLoading,
  faCalendar,
  faChevronRight as farFaChevronRight,
  faChevronLeft as farFaChevronLeft,
  faChevronDoubleRight,
  faChevronDoubleLeft,
  faCalendarAlt,
  faSlidersH,
  faBell
} from '@fortawesome/pro-regular-svg-icons';

import {
  fab
} from '@fortawesome/free-brands-svg-icons';

library.add(
  fab,
  fal,
  far,
  faCubes,
  faBoxFull,
  faBox,
  faBoxOpen,
  faShippingFast,
  faAnchor,
  faEdit,
  faTrashAlt,
  faCog,
  faSearch,
  faSignOutAlt,
  faTag,
  faAddressCard,
  faMoneyBillAlt,
  faHandHoldingUsd,
  faEllipsisH,
  faReceipt,
  faScroll,
  faBell,
  faPlus,
  faMinus,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronCircleRight,
  faChevronCircleDown,
  faCoins,
  faTimes,
  faTimesCircle,
  faBoxUsd,
  faTally,
  faCommentAltLines,
  faInventory,
  faMapMarkerAlt,
  faQuoteLeft,
  faIdCardAlt,
  faBarcodeRead,
  faBrackets,
  faPlusCircle,
  faMinusCircle,
  faCheck,
  faTruckLoading,
  faImages,
  faCloudUpload,
  faChartPie,
  faAsterisk,
  faCheckCircle,
  faCircle,
  faExclamationCircle,
  faInfoCircle,
  faUserCog,
  faDollarSign,
  faMailbox,
  faUserLock,
  faCalendar,
  faParachuteBox,
  farFaChevronRight,
  farFaChevronLeft,
  falFaChevronDown,
  faChevronDoubleRight,
  faChevronDoubleLeft,
  faCalendarAlt,
  faSlidersH
);
